'use strict';

let scratch = [
    {name:'Что такое Scratch', type: 'video', lvl:0, sub: 0, duration: '4 мин', id: 1, bold:'Коротко про Scratch',
        url: 'https://youtu.be/U1T-f0BMcVo',
        project: false,
        engUrl: false,
        descr: 'Вводная информация про scratch.',
        descr2: false},
    {name:'Вращение земли', type: 'word', lvl:0, sub: 0, duration: '12 слайдов', id: 5,  bold:'Движение',
        url: 'https://drive.google.com/file/d/1smKzp5ymzlTRYjZciDRzsroRGnRT2mDA/view?usp=sharing',
        project: 'https://scratch.mit.edu/projects/478523759',
        engUrl: false,
        descr: 'Анимирование вращения земли вокруг солнца. Есть цикл.',
        descr2: false},
    {name:'Майнкрафт ч.1', type: 'task', lvl:0, sub: 0, duration: '', id: 10,  bold:'Логическое мышление',
        url: 'https://studio.code.org/s/aquatic/stage/1/puzzle/1',
        project: false,
        engUrl: false,
        descr: 'Задачи на программирование - хороший и интересный вариант, используйте его в большинстве случаев.',
        descr2: 'Там есть циклы и условные операторы (УО).'},
    {name:'Летучий кот и мышь', type: 'video', lvl:0, sub: 0, duration: '32 мин', id: 15,  bold:'Упор на рисование.',
        url: 'https://youtu.be/qSKt01atYkg',
        project: false,
        engUrl: false,
        descr: 'Простой мультик - рекомендуется как домашнее задание или детям не умеющим читать.',
        descr2: false},
    {name:'Блоки Движение', type: 'video', lvl:0, sub: 0, duration: '14 мин', id: 20,  bold:'Про все блоки "движение".',
        url: 'https://youtu.be/4IRNE--Dyzw',
        project: 'https://levelup-school.github.io/scratch/coordinate/',
        engUrl: false,
        descr: 'Хорошо дать в качестве д\з.',
        descr2: false},
    {name:'Внешний вид', type: 'video', lvl:0, sub: 0, duration: '16 мин', id: 21,  bold:'Про все блоки "внешний вид".',
        url: 'https://youtu.be/73IYkCXmrxY',
        project: false,
        engUrl: false,
        descr: 'Хорошо дать в качестве д\з.',
        descr2: false},
    {name:'События', type: 'video', lvl:0, sub: 0, duration: '10 мин', id: 22,  bold:'Про все блоки "события".',
        url: 'https://youtu.be/ORuK8y37wZ8',
        project: false,
        engUrl: false,
        descr: '',
        descr2: false},
    {name:'Звуки', type: '', lvl:0, sub: 0, duration: '', id: 23,  bold:'Нету материала.<br>Хочет кто сделать?',
        url: '',
        project: false,
        engUrl: false,
        descr: '',
        descr2: false},
    {name:'Редактор костюмов', type: 'video', lvl:0, sub: 0, duration: '18 мин', id: 24,  bold:'Рисуем и изучаем интрументы.',
        url: 'https://youtu.be/1bunkknHvJY',
        project: false,
        engUrl: false,
        descr: 'Изучаем инструменты в редакторе костюма (только векторная графика) - рисуем летучего кота.',
        descr2: false},
    {name:'Убегающий Том', type: 'word', lvl:0, sub: 1, duration: '10 слайдов', id: 30,  bold:'Звук и Размер',
        url: 'https://drive.google.com/file/d/1Zlaw3hvScZ-kAcWily2Z40mhSPqiMuJ2/view?usp=sharing',
        project: 'https://scratch.mit.edu/projects/479207383',
        engUrl: false,
        descr: 'Мультик. Имеется цикл.',
        descr2: false},
    {name:'Квадрат - перемещение', type: 'task', lvl:0, sub: 1, duration: '3 этапа', id: 35,  bold:'Движение, Внешний вид.',
        url: 'https://levelup-school.github.io/scratch/test4/index.html',
        project: false,
        engUrl: false,
        descr: 'Задача на определение координат x,y.',
        descr2: 'А также активно используются блоки плыть и смена костюма.'},
    {name:'', type: '', lvl:0, sub: 2, duration: '', id: 40,  bold:'У нас нету заданий 2-го подуровня...',
        url: '',
        project: false,
        engUrl: false,
        descr: '',
        descr2: false},
    {name:'Мультик про рыбок', type: 'video', lvl:1, sub: 0, duration: '12 мин', id: 45,  bold:'Условный оператор (УО) и циклы.',
        url: 'https://youtu.be/QJoc4kRzKxU',
        project: 'https://scratch.mit.edu/projects/478526741',
        engUrl: false,
        descr: 'Хороший пример, но способным ребятам лучше дать аналогичную презентацию, а не видео.',
        descr2: false},
    {name:'Циклы', type: 'video', lvl:1, sub: 0, duration: '13 мин', id: 47,  bold:'Теория - Циклы.',
        url: 'https://youtu.be/JXDr18G_Ae0',
        project: false,
        engUrl: false,
        descr: 'Это видео про все три цикла.',
        descr2: false},
    {name:'Условный оператор', type: 'video', lvl:1, sub: 0, duration: '13 мин', id: 49,  bold:'Теория про УО.',
        url: 'https://youtu.be/NTV5cAZxcPI',
        project: false,
        engUrl: false,
        descr: 'Это видео про УО и с примерами применения разных сенсоров (условий).',
        descr2: false},
    {name:'Футбол', type: 'video', lvl:1, sub: 1, duration: '14 мин', id: 55,  bold:'УО и циклы.',
        url: 'https://youtu.be/VMaYv1-QkXc',
        project: false,
        engUrl: false,
        descr: 'Хороший пример, используйте это видео.',
        descr2: false},
    {name:'Открытка в подарок', type: 'video', lvl:1, sub: 1, duration: '12 мин', id: 56,  bold:'УО, циклы, рисование.',
        url: 'https://youtu.be/YDQE2JToXtY',
        project: 'https://scratch.mit.edu/projects/478527144',
        engUrl: false,
        descr: 'Много рисования, в остальном это простая программа для закрепления.',
        descr2: false},
    {name:'Танк', type: 'video', lvl:1, sub: 1, duration: '20 мин', id: 58,  bold:'УО, циклы, рисование.',
        url: 'https://youtu.be/LRVHSZ_clzQ',
        project: 'https://scratch.mit.edu/projects/479455896',
        engUrl: false,
        descr: 'Акцент на блоки "движение". В видео настраивается управление танком с отдельно вращающейся башней и танк умеет стрелять.',
        descr2: 'Это интересный проект, его можно дать как д/з после пробного способным ученикам.'},
    {name:'Лабиринт с шариком', type: 'video', lvl:1, sub: 1, duration: '10 мин', id: 60,  bold:'УО, циклы, звук.',
        url: 'https://youtu.be/cESp8NPOtxg',
        project: 'https://scratch.mit.edu/projects/478524828',
        engUrl: false,
        descr: 'Сделана на сенсорах "касается" (спрайта, цвета), движение за мышью.',
        descr2: false},
    {name:'Пинг-Понг', type: 'video', lvl:1, sub: 1, duration: '9 мин', id: 62,  bold:'УО, Циклы.',
        url: 'https://youtu.be/ZxfyGgeqtRw',
        project: "https://scratch.mit.edu/projects/478532514",
        engUrl: false,
        descr: 'Также там используется значение "X мыши", чтобы задать X спрайта.',
        descr2: "Эта игра - твёрдый 1 подуровень для закрепления УО в первую очередь."},
    {name:'Прицел, мышь и танк', type: 'video', lvl:1, sub: 1, duration: '3 этапа', id: 64,  bold:'Циклы, УО.',
        url: 'https://levelup-school.github.io/scratch/test2/',
        project: false,
        engUrl: false,
        descr: 'Задача в 3 этапа. Надо знание блоков "движение" и "внешний вид".',
        descr2: false},
    {name:'', type: '', lvl:1, sub: 2, duration: '', id: 70,  bold:'Пример где блок "если иначе" внутри другого (вложенность УО)',
        url: '',
        project: false,
        engUrl: false,
        descr: '',
        descr2: false},
    {name:'Переменная', type: 'video', lvl:2, sub: 0, duration: '5 мин', id: 90,  bold:'Теория с примером',
        url: '',
        project: false,
        engUrl: false,
        descr: 'Видео про переменную с одним примером (вращение спиннера).',
        descr2: 'Этот видос не обязательно давать первым делом, можно пройти несколько тем, а потом спросить ученика "расскажи своими словами, что такое переменная" и когда он не сможет толком, что-нибудь сказать дайте ему видео посмотреть и скажите, что лучше переменную сравнивать с коробочкой.'},
    {name:'Раздел "Переменные" ч.1', type: 'video', lvl:2, sub: 0, duration: '6 мин', id: 91,  bold:'Теория - подробно про раздел.',
        url: 'https://youtu.be/6AK1SfOUrvM',
        project: false,
        engUrl: false,
        descr: 'Рассказывается про само понятие "переменная", про блоки "изменить", "задать и др.',
        descr2: 'Еще одно видео, которое пытается расскрыть эту значимую тему с другой стороны.'},
    {name:'Раздел "Переменные" ч.2', type: 'video', lvl:2, sub: 0, duration: '8 мин', id: 92,  bold:'"Практическая" теория.',
        url: 'https://youtu.be/ytJstdZYYf4',
        project: false,
        engUrl: false,
        descr: 'Это видео пример, т.е. это более практичный, чем теоретический материал.',
        descr2: false},
    {name:'Секундомер', type: 'word', lvl:2, sub: 0, duration: '', id: 94,  bold:'нету материала, нужна подробная презентация. Есть желающие сделать?',
        url: '',
        project: false,
        engUrl: false,
        descr: '',
        descr2: 'Cкрипт секундомера должны наизусть выучить, в начале каждого урока просите его собрать, до тех пор пока не сделают это самостоятельно и без ошибок!'},
    {name:'Застрели яблоко', type: 'video', lvl:2, sub: 0, duration: '5 мин', id: 96,  bold:'Переменная',
        url: 'https://youtu.be/liw6J22Tw9E',
        project: 'https://scratch.mit.edu/projects/478523357',
        engUrl: false,
        descr: 'Распространенная схема, по нажатию на объект - увеличивается переменная. Успей как можно больше "застрелить" яблок за 10 сек.',
        descr2: 'На подобие класической игры Duck Hunt.'},
    {name:'Повторение - задачи', type: 'task', lvl:2, sub: 0, duration: '6 задач', id: 97,  bold:'Разное.',
        url: 'https://levelup-school.github.io/scratch/test1/',
        project: 'https://scratch.mit.edu/projects/478593021',
        engUrl: false,
        descr: 'Простейшная задача на переменную, сложноватые задачи на циклы и блоки движения/ внешний вид.',
        descr2: false},
    {name:'Кот, дракон и пончик', type: 'video', lvl:2, sub: 1, duration: '11 мин', id: 100,  bold:'Переменная',
        url: 'https://youtu.be/cN48OT-6RSI',
        project: 'https://scratch.mit.edu/projects/478523016',
        engUrl: false,
        descr: 'Игра в целом обходится и без переменной, но переменным применение всегда найдется. В видео собран обычный скрипт секундомера.',
        descr2: false},
    {name:'Отгадай число', type: 'video', lvl:2, sub: 1, duration: '12 мин', id: 102,  bold:'Переменная, спросить, объединить.',
        url: 'https://youtu.be/eF9uhByNiz4',
        project: 'https://scratch.mit.edu/projects/478536781',
        engUrl: false,
        descr: 'Хорошая и простая демонстрация использования переменной.',
        descr2: 'Предложите уменьшить кол-во попыток, чтобы было сложнее играть.'},
    {name:'Калькулятор', type: 'video', lvl:2, sub: 0, duration: '4 мин', id: 104,  bold:'Переменная, спросить, операторы.',
        url: 'https://youtu.be/_q_nMpZAzPo',
        project: 'https://scratch.mit.edu/projects/478524231',
        engUrl: false,
        descr: 'Хороший пример использования переменной, но способным ребятам лучше дать аналогичную презентацию, а не видео.',
        descr2: false},
    {name:'Калькулятор', type: '', lvl:2, sub: 1, duration: '', id: 105,  bold:'Кто-нибудь сделает подробную презентацию?',
        url: '',
        project: 'https://scratch.mit.edu/projects/478524231',
        engUrl: false,
        descr: 'Хороший пример использования переменной.',
        descr2: 'Более способному ученику - презентация, послабее - видео.'},
    {name:'Не просто кликер', type: 'task', lvl:2, sub: 1, duration: '3 этапа', id: 107,  bold:'Переменная, УО.',
        url: 'https://levelup-school.github.io/scratch/test3/',
        project: 'https://scratch.mit.edu/projects/480178076',
        engUrl: false,
        descr: 'Два задания на переменную и три связанных с УО.',
        descr2: false},
    {name:'Летучий кот', type: 'video', lvl:2, sub: 1, duration: '15 мин', id: 108,  bold:'Переменные.',
        url: 'https://youtu.be/Gf6QA6Cs3zc',
        project: 'https://scratch.mit.edu/projects/478525126',
        engUrl: false,
        descr: 'Использовано две простых переменных без сложной математики и с простыми условиями "Если".',
        descr2: false},
    {name:'Калькулятор', type: 'word', lvl:2, sub: 2, duration: '', id: 110,  bold:'Со всеми 4-мя действиями, кто сделает?',
        url: '',
        project: false,
        engUrl: false,
        descr: '',
        descr2: false},
    {name:'Морковкопад', type: 'video', lvl:2, sub: 2, duration: '41 мин', id: 112,  bold:'Переменные.',
        url: 'https://youtu.be/mvwZYLas09o',
        project: 'https://scratch.mit.edu/projects/481675288',
        engUrl: false,
        descr: 'Вроде не сложный но объемный проект, его нужно давать после закрепления темы "переменные".',
        descr2: false},
    {name:'RedGreens', type: 'video', lvl:2, sub: 3, duration: '22 мин', id: 120,  bold:'Переменные, математика.',
        url: 'https://youtu.be/QdIoqWvWTeM',
        project: 'https://scratch.mit.edu/projects/478514427',
        engUrl: false,
        descr: 'Программа не большая, но хватает математики, что усложняет игру.',
        descr2: 'Можно спросить как ученик понял все эти вычисления и почему так сделано.'},
    {name:'Футбол', type: 'video', lvl:2, sub: 3, duration: '16 мин', id: 122,  bold:'Переменные.',
        url: 'https://youtu.be/qx5pyTY08r0',
        project: 'https://scratch.mit.edu/projects/476818536',
        engUrl: false,
        descr: 'Есть довольная сложная  для детей схема передачи свойств объекта. В скрэтче есть специальный блок для этого, как вариант можно познакомить заодно с ним. (Направление от спрайт1) ',
        descr2: 'Также можно доработать игру - сделать вратаря, условия для победы и поражения.'},
    {name:'Пикассо', type: 'video', lvl:3, sub: 1, duration: '9 мин', id: 140,  bold:'Клоны, Перо.',
        url: 'https://youtu.be/tXrVoq0W9to',
        project: 'https://scratch.mit.edu/projects/478530462',
        engUrl: false,
        descr: 'Легкое и интересное занятие, тут используется дополнительное расширение "перо" - что позволяет привнести разнообразие и расширить возможности Scratch, но по программе знать про перо не обязательно.',
        descr2: false},
    {name:'Обед циплёнка', type: 'word', lvl:3, sub: 1, duration: '20 мин', id: 140,  bold:'Клоны.',
        url: 'https://drive.google.com/file/d/1QLnVLzhDyzOR1drMcA6AjoZYnrri72QQ/view?usp=sharing',
        project: 'https://scratch.mit.edu/projects/478628055',
        engUrl: false,
        descr: 'Относительно не сложная презентация, есть переменные.',
        descr2: false},
    {name:'Cлучайный клон', type: 'task', lvl:3, sub: 1, duration: '3 этапа', id: 155,  bold:'Клоны, Переменная',
        url: 'https://levelup-school.github.io/scratch/test5/',
        project: 'https://scratch.mit.edu/projects/480387309',
        engUrl: false,
        descr: 'Не сложная задача с клонами их поведением и переменной.',
        descr2: false},
    {name:'Атака пришельцев', type: 'video', lvl:3, sub: 2, duration: '20 мин', id: 160,  bold:'Клоны.',
        url: 'https://youtu.be/rJwypDvQ2bY',
        project: 'https://scratch.mit.edu/projects/478517889',
        engUrl: false,
        descr: 'Клоны использованы для генерации врагов. Хороший пример для твердого 1-го уровня или начала 2-го.',
        descr2: 'Незначительное использование переменных (очки и жизни).'},
    {name:'Найди настоящего кота', type: '', lvl:3, sub: 2, duration: ' мин', id: 140,  bold:'Проект есть. Сделает кто?',
        url: '',
        project: 'https://scratch.mit.edu/projects/479708088',
        engUrl: false,
        descr: 'Игра на 2-х игроков. Хороший и наглядный пример использования клонов. Трудность в понимании может быть с "технической" переменной созданной для предотвращения срабатывания одного скрипта несколько раз при нажатии на мышь.',
        descr2: false},
    {name:'', type: 'video', lvl:3, sub: 2, duration: ' мин', id: 140,  bold:'',
        url: '',
        project: '',
        engUrl: false,
        descr: '',
        descr2: false},

    ];

module.exports = scratch;